version: '3.8'

services:
  backend:
    volumes:
      - ./chargingplatform:/app
    working_dir: /app
    command: mvn spring-boot:run -Dspring-boot.run.fork=false
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chargingplatform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_FLYWAY_ENABLED: true
      SPRING_PROFILES_ACTIVE: dev
