version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: chargingplatform-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./chargingplatform
      dockerfile: Dockerfile
    container_name: chargingplatform-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      HOSTNAME: ${HOSTNAME}
      FRONTEND_DOCKER_PORT: ${FRONTEND_DOCKER_PORT}
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url" : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DB",
          "spring.datasource.username" : "$POSTGRES_USER",
          "spring.datasource.password" : "$POSTGRES_PASSWORD",
          "spring.datasource.driver-class-name" : "org.postgresql.Driver",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "spring.jpa.show-sql" : "true",
          "spring.jpa.properties.hibernate.format_sql" : "true",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "server.port" : "$BACKEND_DOCKER_PORT"
        }'
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    volumes:
      - .m2:/root/.m2

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chargingplatform-frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - $FRONTEND_LOCAL_PORT:$FRONTEND_DOCKER_PORT

volumes:
  postgres_data: 