name: Deploy no Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout of repository
        uses: actions/checkout@v3

      - name: Getting into the project directory
        run: |
          cd .

      - name: Criar arquivo .env
        run: |
          cat > .env <<EOF
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          BACKEND_PORT=${{ secrets.BACKEND_PORT }}
          FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
          EOF

      - name: Stop previous containers
        run: |
          docker compose down || true

      - name: Pull de imagens, se for o caso
        run: |
          docker compose pull || true

      - name: Run app with Docker Compose
        run: |
          docker compose up -d --build